// Aula em Dia — fragmento de config Tailwind.
// Tema noturno via seletor [data-tema="escuro"]; as cores viram var() para trocar em runtime.
module.exports = {
  darkMode: ['selector', '[data-tema="escuro"]'],
  theme: {
    extend: {
      colors: {
        amarelo: '#FFD032',
        'tinta-amarelo': '#0E1626',
        'tela': 'var(--tela)',
        'caixa': 'var(--caixa)',
        'cartao': 'var(--cartao)',
        'linha': 'var(--linha)',
        'texto': 'var(--texto)',
        'texto-medio': 'var(--texto-medio)',
        'suave': 'var(--suave)',
        'fraco': 'var(--fraco)',
        'inativo': 'var(--inativo)',
        'topo': 'var(--topo)',
        'topo-texto': 'var(--topo-texto)',
        'topo-fraco': 'var(--topo-fraco)',
        'topo-cartao': 'var(--topo-cartao)',
        'elevado': 'var(--elevado)',
        'elevado-suave': 'var(--elevado-suave)',
        'botao': 'var(--botao)',
        'botao-texto': 'var(--botao-texto)',
        'botao-hover': 'var(--botao-hover)',
        'desab-fg': 'var(--desab-fg)',
        'hover': 'var(--hover)',
        'amarelo-fraco': 'var(--amarelo-fraco)',
        'vermelho': 'var(--vermelho)',
        'vermelho-fraco': 'var(--vermelho-fraco)',
        'verde': 'var(--verde)',
      },
      fontFamily: { sans: ["Satoshi", "system-ui", "sans-serif"] },
      fontSize: {
        micro: ['9px', { lineHeight: '1', letterSpacing: '0.16em' }],
        eyebrow: ['10px', { lineHeight: '1', letterSpacing: '0.18em' }],
        nota: ['11.5px', { lineHeight: '1.55' }],
        legenda: ['12px', { lineHeight: '1.4' }],
        corpo: ['12.5px', { lineHeight: '1.5' }],
        aba: ['13px', { lineHeight: '1', letterSpacing: '0.01em' }],
        nome: ['15px', { lineHeight: '1.25' }],
        botao: ['15.5px', { lineHeight: '1' }],
        titulo: ['24px', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        heroi: ['30px', { lineHeight: '1', letterSpacing: '-0.04em' }],
      },
      borderRadius: { micro: '5px', contador: '6px', cartao: '8px', pastilha: '13px', pilula: '99px' },
      height: { primario: '52px', secundario: '44px', aba: '42px', curva: '58px' },
      boxShadow: {
        vidro: 'inset 0 1.5px 1.5px rgba(255,255,255,.7), inset 0 -1.5px 1.5px rgba(255,255,255,.34), inset 1.5px 0 1.5px rgba(255,255,255,.2), inset -1.5px 0 1.5px rgba(255,255,255,.2), 0 3px 10px rgba(0,0,0,.32)',
      },
    },
  },
};
